### ISSUE TITLE
ups pico with hass 0.86.0

### ISSUE THREAD

**Issue by reaper7** [milanvo/hass-components#1]
ups pico (voltage, temperature etc) no longer work with new hass 0.86.0 (switches/leds works)

this is hass log:
```
2019-01-23 23:31:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 336, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: ups_pico.voltBat
2019-01-23 23:31:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 336, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: ups_pico.pwrMode
2019-01-23 23:31:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 336, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: ups_pico.voltRpi
2019-01-23 23:31:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 336, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: ups_pico.tempNtc1

```

**Comment by milanvo** [comment]
Hi,

just updated my HA to 0.86.3 and see the same issue - what a surprise 😉
I make fix e03e028304a59b098cf07a4d843a8ec2b89ce67a for the component, please can you test it ? (pull, clone or download new version)

**Comment by milanvo** [comment]
New sensor entity names:
```
  - entity: ups_pico.pwr_mode
  - entity: ups_pico.volt_rpi
  - entity: ups_pico.volt_bat
  - entity: ups_pico.temp_ntc1
```
Switches should be the same

**Comment by reaper7** [comment]
Tnx, now works ok :)
