### ISSUE TITLE
ups pico with hass 0.88.0

### ISSUE THREAD

**Issue by reaper7** [milanvo/hass-components#3]
looks like we have next problem with new HAAA 0.88.0 :(

```
2019-02-20 22:42:26 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.ups_pico.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'custom_components.ups_pico.switch'; 'custom_components.ups_pico' is not a package
```

and
```
Integrations need to be in their own folder. Change switch/ups_pico.py to ups_pico/switch.py. This will stop working soon.
```

**Comment by milanvo** [comment]
Fixed and now testing, looks OK.

Just directory structure change / move is necessary.
````
renamed:    custom_components/ups_pico.py -> custom_components/ups_pico/__init__.py
renamed:    custom_components/switch/ups_pico.py -> custom_components/ups_pico/switch.py
````

Repo and README is updated https://github.com/milanvo/hass-components/commit/7d402f059587deaecc5c6f95b9240c15eab86fcf
